<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.ibeetl</groupId>
    <artifactId>beetlsql</artifactId>
    <version>3.32-RELEASE</version>
    <parent>
        <groupId>com.ibeetl</groupId>
        <artifactId>beetlsql-all</artifactId>
        <version>3.32-RELEASE</version>
    </parent>
    <properties>
        <beetlsql.version>3.32-RELEASE</beetlsql.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>sql-core</artifactId>
            <version>${beetlsql.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>sql-gen</artifactId>
            <version>${beetlsql.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>sql-fetch</artifactId>
            <version>${beetlsql.version}</version>
        </dependency>
        <dependency>
            <groupId>com.ibeetl</groupId>
            <artifactId>sql-mapper</artifactId>
            <version>${beetlsql.version}</version>
        </dependency>
    </dependencies>

</project>
