<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ibeetl</groupId>
        <artifactId>sql-db-support</artifactId>
        <version>3.12.10-RELEASE</version>
    </parent>

    <groupId>com.ibeetl</groupId>
    <artifactId>couchbase</artifactId>
    <version>3.12.10-RELEASE</version>
    <dependencies>
        <!-- 此驱动是商业驱动试用版 https://www.cdata.com/ -->
        <dependency>
            <groupId>couchbase</groupId>
            <artifactId>couchbase</artifactId>
            <version>4</version>
            <scope>system</scope>
            <systemPath>/Users/xiandafu/Downloads/CouchbaseJDBCDriver/lib/cdata.jdbc.couchbase.jar</systemPath>
        </dependency>
    </dependencies>

    
</project>