<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ibeetl</groupId>
        <artifactId>sql-saga</artifactId>
        <version>3.1.1-RELEASE</version>
    </parent>
    <packaging>pom</packaging>

    <groupId>com.ibeetl</groupId>
    <artifactId>sql-saga-level3</artifactId>
    <version>3.1.1-RELEASE</version>
    <modules>
        <module>sql-saga-microservice-client</module>
        <module>sql-saga-microservice-server</module>
        <module>sql-saga-microservice-demo</module>
    </modules>


    
</project>