ENGINE=org.beetl.sql.core.engine.BeetlSQLTemplateEngine

#SQL脚本中使用的定界符和占位符，#{}输出?, ${} 文本输出
DELIMITER_PLACEHOLDER_START=#{
DELIMITER_PLACEHOLDER_END=}
# 模仿注释
DELIMITER_STATEMENT_START=-- @
DELIMITER_STATEMENT_END=
DELIMITER_PLACEHOLDER_START2=${
DELIMITER_PLACEHOLDER_END2=}
CHARSET=UTF-8
#Beetl模板引擎，不支持html&xml 自定义标签,提高解析速度
HTML_TAG_SUPPORT = false

## 扩展函数

FN.use = org.beetl.sql.core.engine.UseFunction
FN.globalUse = org.beetl.sql.core.engine.GlobalUseFunction
FN.text = org.beetl.sql.core.engine.TextFunction
FN.join = org.beetl.sql.ext.JoinFunction
FN.isEmpty=org.beetl.sql.core.engine.EmptyExpressionFunction
FN.isNotEmpty=org.beetl.sql.core.engine.NotEmptyExpressionFunction
FN.isBlank=org.beetl.sql.core.engine.IsBlank
FN.db.dynamicSql=org.beetl.sql.core.engine.DynamicSqlFunction
FN.page=org.beetl.sql.core.engine.PageQueryFuntion
FN.jsonMapping=org.beetl.sql.core.engine.MappingFunction
TAG.trim= org.beetl.sql.core.engine.TrimTag
TAG.pageTag= org.beetl.sql.core.engine.PageQueryTag
TAG.pageIgnoreTag= org.beetl.sql.core.engine.PageQueryIgnoreTag
TAG.where= org.beetl.sql.core.engine.WhereTag

## 内部使用
FN.db.testNull=org.beetl.sql.core.engine.TestNullFunction
FN.db.testColNull=org.beetl.sql.core.engine.TestColNullFunction
FN.db.testVarNull=org.beetl.sql.core.engine.TestVarNullFunction

## 错误处理器，输出sql模板错误原因
ERROR_HANDLER = org.beetl.sql.core.engine.BeetlSQLTemplateExceptionHandler

FT.jdbc =org.beetl.sql.core.engine.JdbcTypeFormat


# 自动检测sql文件变化
PRODUCT_MODE = false

# 范围是否从0开始，默认从1开始
OFFSET_START_ZERO =  false

# Mapper方法 中@Sql或者@SqlTemplate 长度.设置-1不限制
MAPPER_SQL_MAX_LENGTH=-1
