package org.beetl.sql.core.nosql;

import org.beetl.sql.clazz.kit.BeanKit;
import org.beetl.sql.core.db.AbstractDBStyle;
import org.beetl.sql.core.db.DBAutoGeneratedSql;
import org.beetl.sql.core.db.DBType;
import org.beetl.sql.core.page.DefaultPageRequest;
import org.beetl.sql.core.page.PageRequest;
import org.beetl.sql.core.range.RangeSql;

import java.lang.annotation.Annotation;
import java.util.List;
import java.util.Map;

/**
 * 注意，CassandraSqlStyle不支持自动生成翻页
 *
 * @author xiandafu
 */
public class CassandraSqlStyle extends AbstractDBStyle {

    CassandraRangeSql cassandraRangeSql = null;

    public CassandraSqlStyle() {
        super();
        cassandraRangeSql = new CassandraRangeSql(this);
    }


    @Override
    public int getIdType(Class c, String idProperty) {
        List<Annotation> ans = BeanKit.getAllAnnotation(c, idProperty);
        int idType = DBType.ID_ASSIGN; //默认是自增长
        return idType;
    }

    @Override
    public String getName() {
        return "cassandra";
    }

    @Override
    public int getDBType() {
        return DBType.DB_CASSANDRA;
    }

    @Override
    public RangeSql getRangeSql() {
        return cassandraRangeSql;
    }

    /**
     *  Cassandra 翻页不支持，然而，开发者可以根据自己项目特点实现自动翻页语句
	 *  这是一个简单例子演示向前翻页，例子假设表中有一个自增seq例子，当完成下一页功能，生成的sql查询是 seq>offset limit 5 来实现
	 *
	 *  开发者应该负责记录这个seq字段并在下一页时候，作为offset参数传递进来
	 *
	 *  如果需要完成上一页，下一页，需要开发者自己完成seq<offset limit 5 这样功能
	 *
	 *  建议开发者通过mapper方法自己定义实现上一页，下一页，不要使用RangeSql！这里只是个思路
     *
     */
    public static class CassandraRangeSql implements RangeSql {
        AbstractDBStyle sqlStyle = null;

        public CassandraRangeSql(AbstractDBStyle style) {
            this.sqlStyle = style;
        }

        @Override
        public String toRange(String jdbcSql, Object objOffset, Long limit) {

			return jdbcSql+" and seq>"+objOffset+"  order by seq asc limit "+limit;

        }

        @Override
        public String toTemplateRange(Class mapping, String template) {
			return template +" and seq>"+sqlStyle.appendExpress(DBAutoGeneratedSql.OFFSET )+"  order by seq asc limit "+sqlStyle.appendExpress(DBAutoGeneratedSql.PAGE_SIZE );

        }

        @Override
        public void addTemplateRangeParas(Map<String, Object> paras, Object offset, long size) {
			Long seq = (Long)offset;
			paras.put(DBAutoGeneratedSql.OFFSET, seq);
			paras.put(DBAutoGeneratedSql.PAGE_SIZE, size);
        }
    }

	public static class  OnlyNextPageRequest extends DefaultPageRequest {

		public OnlyNextPageRequest(long maxRowId,int limit){
			this.pageSize = limit;
			this.pageNumber = maxRowId;
			this.orderBy= null;
			this.listRequired=true;
			this.totalRequired=true;

		}
		public  Object getStart(boolean offsetStartZero){
			return getPageNumber();
		}
	}


}
