spring.application.name=orderSystem

# 配置俩个topic，saga-server和当前服务，当前服务监听topic取决于application.name
# 当前服务监听${beetlsql-saga.kafka.client-topic-prefix}+ ${spring.application.name}
beetlsql-saga.kafka.client-topic-prefix=saga-client
beetlsql-saga.kafka.server-topic=saga-server-topic


server.port=8080

#数据库配置
spring.datasource.url=jdbc:h2:mem:dbtest;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# kafka配置
spring.kafka.bootstrapServers=${kafka_server:127.0.0.1:9092}
spring.kafka.consumer.group-id=${kafka_group:saga-group}
spring.kafka.consumer.max-poll-records=100
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=100
spring.kafka.listener.type=batch



beetlsql.sqlManagers=mySqlManager
beetlsql.mySqlManager.ds=datasource
beetlsql.mySqlManager.basePackage=org.beetl.sql.saga.ms.server
beetlsql.mySqlManager.dbStyle=org.beetl.sql.core.db.H2Style


