package org.beetl.sql.core.engine;

import org.beetl.core.tag.Tag;
import org.beetl.sql.core.db.DBAutoGeneratedSql;

import java.io.IOException;

public class PageQueryIgnoreTag extends Tag {

	//Override
	public void render() {
		Object o = ctx.getGlobal(DBAutoGeneratedSql.PAGE);
		if(o!=null){
			try {
				this.bw.writeString(" ");
			} catch (IOException e) {
				//不可能发生
				e.printStackTrace();
			}

		} else {
			this.doBodyRender();

		}
	}

}