<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ibeetl</groupId>
        <artifactId>sql-integration</artifactId>
        <version>3.1.5-RELEASE</version>
    </parent>

    <groupId>com.ibeetl</groupId>
    <artifactId>sql-act</artifactId>
    <version>3.1.5-RELEASE</version>
    <properties>
        <act-sql-common.version>1.6.0</act-sql-common.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
        <scm.url>git@github.com:actframework/act-maven-parent.git</scm.url>

        <maven-compiler-plugin.version>3.7.0</maven-compiler-plugin.version>
        <maven-javadoc-plugin.version>3.0.0-M1</maven-javadoc-plugin.version>
        <maven-source-plugin.version>3.0.1</maven-source-plugin.version>
        <nexus-staging-maven-plugin.version>1.6.8</nexus-staging-maven-plugin.version>

        <buildnumber-maven-plugin.version>1.4</buildnumber-maven-plugin.version>
        <jacoco-maven-plugin.version>0.7.9</jacoco-maven-plugin.version>
        <license-maven-plugin.version>1.13</license-maven-plugin.version>
        <markdown-doclet.version>1.4</markdown-doclet.version>

        <junit.version>4.12</junit.version>
        <mockito.version>2.9.0</mockito.version>
        <slf4j-api.version>1.7.25</slf4j-api.version>

        <osgl-version.version>2.0.0-BETA-4-JAVA7</osgl-version.version>
        <osgl-ut.version>2.0.0-BETA-4-JAVA7</osgl-ut.version>
        <act.version>1.8.32</act.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j-api.version}</version>
        </dependency>

        <dependency>
            <groupId>org.osgl</groupId>
            <artifactId>osgl-version</artifactId>
            <version>${osgl-version.version}</version>
        </dependency>

        <dependency>
            <groupId>org.osgl</groupId>
            <artifactId>osgl-ut</artifactId>
            <version>${osgl-ut.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.actframework</groupId>
            <artifactId>act</artifactId>
            <version>${act.version}</version>
        </dependency>

        <dependency>
            <groupId>org.actframework</groupId>
            <artifactId>act</artifactId>
            <version>${act.version}</version>
        </dependency>

        <dependency>
            <groupId>org.actframework</groupId>
            <artifactId>act-sql-common</artifactId>
            <version>${act-sql-common.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>org.antlr</groupId>
                    <artifactId>antlr4-runtime</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

    </dependencies>

    
</project>