server.port=18081
server.shutdown=graceful

#数据库配置
spring.datasource.url=jdbc:h2:file:~/.h2/saga-server;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# kafka配置
spring.kafka.bootstrapServers=${kafka_server:127.0.0.1:9092}
spring.kafka.consumer.group-id=${kafka_group:saga-group}
spring.kafka.consumer.max-poll-records=100
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.enable-auto-commit=true
spring.kafka.consumer.auto-commit-interval=100
spring.kafka.listener.type=batch



beetlsql-saga.kafka.server-topic=saga-server-topic
beetlsql-saga.kafka.client-topic-prefix=saga-client


beetlsql.sqlManagers=mySqlManager
beetlsql.mySqlManager.ds=datasource
beetlsql.mySqlManager.basePackage=org.beetl.sql.saga.ms.server
beetlsql.mySqlManager.dbStyle=org.beetl.sql.core.db.H2Style





